Repository CodeYourFuture/project-quiz, pull requests merged in 2020-07, with the labels that each got.

#90 Seed db
  data-import/quizzes/quizzes.js
  readme.md
Labels: backend

#93 Fetch data from backend to frontend
  client/src/components/Question.js
  client/src/components/Quiz.js
  client/src/components/ReviewAnswers.js
  client/src/components/retrieveQuizData.js
  client/src/data/cssQuiz.json
  client/src/data/dummy.json
  client/src/data/jsQuiz.json
  client/src/index.js
  data-import/quizzes/quizzes.js
  models/quiz.js
  routes/quizzes.js
Labels: backend, frontend

#95 Updated README file.
  README.md
  client/src/components/About.js
  client/src/components/Footer.js
  readme.md
Labels: documentation

#94 Move the shuffle function from client side to the backend side
  helpers/shuffle.js
  routes/quizzes.js
Labels: backend, frontend

#97 Added Node.js quiz questions and answers.
  client/src/components/Header.js
  client/src/components/Home.js
  client/src/components/Quiz.js
  data-import/quizzes/quizzes.js
Labels: backend, frontend
