Repository CodeYourFuture/project-quiz, pull requests merged in 2020-04, with the labels that each got.

#9 Add bootstrap
  package-lock.json
  package.json
  src/index.js
Labels: tooling

#13 Add SCSS and change stylesheet extentions to .scss
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/index.js
  src/index.scss
Labels: tooling

#8 Update ReadMe file.
  README.md
  package-lock.json
Labels: documentation

#12 Add prettier formater
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
Labels: tooling

#25 Add Editor config
  .editorconfig
  package-lock.json
Labels: tooling

#28 Display questions
  src/App.js
  src/data/dummy.json
Labels: feature

#29 Show answers for each question.
  src/App.js
Labels: feature

#30 Display answers with questions on main page with form inputs
  src/App.js
Labels: feature

#32 Submit button
  src/App.js
Labels: feature

#33 Update UI to use react bootstrap.
  src/App.js
Labels: feature

#34 Install react-router-dom
  README.md
  package-lock.json
  package.json
Labels: tooling

#36 Create components templates.
  src/components/About.js
  src/components/Footer.js
  src/components/Home.js
  src/components/Navbar.js
  src/components/Quiz.js
Labels: documentation

#37 Create routes
  src/App.js
  src/components/Quiz.js
  src/routes/index.js
Labels: feature

#43 Extract question into separate component
  src/components/Question.js
  src/components/Quiz.js
Labels: feature

#39 Create footer
  package-lock.json
  package.json
  src/App.js
  src/App.scss
  src/components/Footer.js
  src/components/Home.js
  src/index.scss
Labels: feature

#45 Display one question per page
  src/components/Question.js
  src/components/Quiz.js
Labels: feature

#49 Shuffle array of questions and array of answers for each question
  src/components/Quiz.js
  src/helpers/shuffle.js
Labels: feature

#46 Create about page
  src/components/About.js
Labels: feature

#51 Change onClick to onChange.
  src/components/Question.js
Labels: bug

#44 Home page
  src/App.css
  src/App.min.css
  src/components/Home.js
Labels: feature

#52 Create css and js quiz data
  src/data/cssQuiz.json
  src/data/jsQuiz.json
Labels: feature
